import { NextRequest, NextResponse } from "next/server"
import { getSharePointAccessToken, ensureFolderExists, uploadFileToSharePoint } from "@/lib/sharepoint"

export async function POST(request: NextRequest) {
  try {
    const data = await request.json()
    const { candidateName, checkDate, pathway, bs7671Status, itStatus, experience, adminNotes } = data

    if (!candidateName) {
      return NextResponse.json({ error: "Candidate name is required" }, { status: 400 })
    }

    // Get SharePoint access token
    const accessToken = await getSharePointAccessToken()

    // Create folder structure: Pathway-Checks/{CandidateName}/
    const sanitizedName = candidateName.replace(/[^a-zA-Z0-9\s-]/g, "").trim()
    const folderPath = `Pathway-Checks/${sanitizedName}`
    
    await ensureFolderExists(accessToken, "Pathway-Checks")
    await ensureFolderExists(accessToken, folderPath)

    // Generate PDF content as HTML (will be saved as HTML file that can be printed to PDF)
    const timestamp = new Date().toISOString().split("T")[0]
    const fileName = `Pathway-Check_${timestamp}.html`

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>EWA Pathway Check - ${candidateName}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
    h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }
    .logo { font-size: 24px; font-weight: bold; color: #1e40af; }
    .date { color: #6b7280; }
    .section { background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .field { margin: 10px 0; }
    .label { font-weight: bold; color: #374151; }
    .value { color: #111827; }
    .pathway-result { background: #dbeafe; border: 2px solid #1e40af; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .pathway-code { font-size: 24px; font-weight: bold; color: #1e40af; }
    .admin-notes { background: #fef3c7; border: 1px solid #f59e0b; padding: 15px; border-radius: 8px; margin: 20px 0; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">EWA Tracker</div>
    <div class="date">Generated: ${new Date().toLocaleDateString("en-GB")}</div>
  </div>
  
  <h1>Pathway Check Result</h1>
  
  <div class="section">
    <h2>Candidate Details</h2>
    <div class="field"><span class="label">Name:</span> <span class="value">${candidateName}</span></div>
    <div class="field"><span class="label">Check Date:</span> <span class="value">${checkDate || new Date().toLocaleDateString("en-GB")}</span></div>
  </div>
  
  <div class="section">
    <h2>Qualification Status</h2>
    <div class="field"><span class="label">BS 7671 Status:</span> <span class="value">${bs7671Status || "Not specified"}</span></div>
    <div class="field"><span class="label">Inspection & Testing:</span> <span class="value">${itStatus || "Not specified"}</span></div>
    <div class="field"><span class="label">Experience:</span> <span class="value">${experience || "Not specified"}</span></div>
  </div>
  
  <div class="pathway-result">
    <h2>Recommended Pathway</h2>
    <div class="pathway-code">${pathway || "Not determined"}</div>
  </div>
  
  ${adminNotes ? `
  <div class="admin-notes">
    <h2>Admin Notes</h2>
    <p>${adminNotes.replace(/\n/g, "<br>")}</p>
  </div>
  ` : ""}
  
  <p style="color: #6b7280; font-size: 12px; margin-top: 40px;">
    This document was generated by EWA Tracker Pathway Checker. 
    For queries, contact support@ewatracker.co.uk
  </p>
</body>
</html>
`

    // Upload to SharePoint
    const fileBuffer = Buffer.from(htmlContent, "utf-8")
    await uploadFileToSharePoint(accessToken, folderPath, fileName, fileBuffer)

    return NextResponse.json({ 
      success: true, 
      message: `Pathway check saved to SharePoint: ${folderPath}/${fileName}`,
      filePath: `${folderPath}/${fileName}`
    })

  } catch (error) {
    console.error("Error saving pathway check to SharePoint:", error)
    return NextResponse.json(
      { error: "Failed to save to SharePoint", details: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    )
  }
}
