// Automated, personalised eligibility-response email.
//
// Triggered from /api/eligibility-checker/log whenever a candidate completes an
// eligibility check (AI wizard OR website form) and provided an email address.
// The prose is generated by AI (Vercel AI Gateway, zero-config — same setup as
// the site chatbot) grounded in the candidate's own answers, then delivered via
// the existing Resend setup.
//
// DESIGN PRINCIPLE: the AI only COMMUNICATES; it never JUDGES.
// - The "at a glance" summary and all factual claims are built deterministically
//   in code from the structured answers — the model cannot invent them.
// - The model writes only short, warm framing paragraphs and the subject line,
//   under strict rules that forbid qualification-equivalence conclusions,
//   invented services, and guarantees.

import { generateObject } from "ai"
import { z } from "zod"
import { ASSISTANT_KNOWLEDGE } from "@/lib/assistant/knowledge"

// The shape of the metadata the /log route already assembles.
export interface EligibilityLogMetadata {
  candidateName?: string
  email?: string
  phone?: string
  experience?: string
  level2Qualification?: string
  level3Qualification?: string
  bs7671Status?: string
  itStatus?: string
  workType?: string
  pathway?: string
  eligibilityResult?: string
  recommendations?: string
  source?: string
}

const FROM = process.env.RESEND_FROM_EMAIL || "EWA Tracker <bookings@ewatracker.co.uk>"
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "admin@ewatracker.co.uk"
const SITE_URL = (process.env.NEXT_PUBLIC_MARKETING_WEBSITE_URL || "https://www.ewatracker.co.uk").replace(/\/$/, "")

const QUALIFICATION_NAME = "EAL Level 3 Electrotechnical Experienced Worker Qualification"

// Basic sanity check so we never try to email an obviously invalid address.
function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

async function getResend() {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) throw new Error("RESEND_API_KEY environment variable is not set")
  const { Resend } = await import("resend")
  return new Resend(apiKey)
}

// Escape user/AI-provided text before putting it into the HTML template.
function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

// The internal pathway values carry a private suffix (e.g. 603/5982/1DZ). The
// candidate should only ever see the published accreditation number 603/5982/1.
function cleanPathwayCode(pathway?: string): string | null {
  const match = (pathway || "").match(/\d{3}\/\d{4}\/\d/)
  return match ? match[0] : null
}

// Softer, non-committal phrasing for the indicative result. Never definitive.
function friendlyResult(result?: string): string {
  const r = (result || "").toUpperCase()
  if (r.includes("SUITABLE")) return "Potentially suitable for the EWA (subject to verification)"
  return "Further review recommended to confirm your starting point"
}

// Treat "None", "No ...", "Unsure", blanks etc. as "not held / not a qualification".
function isMeaningful(value?: string): boolean {
  const s = (value || "").trim().toLowerCase()
  if (!s) return false
  return !/^(none|no\b|no |not |unsure|n\/a|\(not given\))/.test(s)
}

// Build the "at a glance" summary DETERMINISTICALLY from the answers. This is
// the single source of factual claims in the email — the AI never touches it,
// so it cannot turn self-declared info into a formal centre judgement.
function buildHighlights(meta: EligibilityLogMetadata): string[] {
  const needsEdition = /no 18th/i.test(meta.bs7671Status || "")
  const needsIT = /no inspection/i.test(meta.itStatus || "")
  const highlights: string[] = []

  if (isMeaningful(meta.experience)) {
    highlights.push(`${meta.experience} electrical experience reported`)
  }
  if (isMeaningful(meta.level2Qualification)) {
    highlights.push(`${meta.level2Qualification} reported`)
  }
  if (isMeaningful(meta.level3Qualification)) {
    highlights.push(`${meta.level3Qualification} reported`)
  }
  highlights.push(needsEdition ? "18th Edition (BS 7671) not currently held" : "18th Edition (BS 7671) reported")
  highlights.push(needsIT ? "Inspection & Testing not currently held" : "Inspection & Testing reported")
  highlights.push(`Initial indication: ${friendlyResult(meta.eligibilityResult)}`)
  highlights.push("Next step: complete the full Skills Scan and provide qualification evidence for verification")

  return highlights
}

const emailSchema = z.object({
  subject: z.string().describe("Concise, personalised email subject line. No emojis."),
  preheader: z.string().describe("Short preview text shown in the inbox, under 90 characters."),
  greetingName: z.string().describe("The first name to greet the candidate by, or 'there' if unknown."),
  paragraphs: z
    .array(z.string())
    .min(2)
    .max(3)
    .describe(
      "2-3 short, warm framing paragraphs of plain text (no HTML, no markdown). Do NOT itemise or restate all the candidate's answers — the summary below the paragraphs already lists them.",
    ),
})

type GeneratedEmail = z.infer<typeof emailSchema>

// Decide the primary call-to-action from the eligibility result.
function pickCta(result: string): { label: string; url: string } {
  const r = (result || "").toUpperCase()
  if (r.includes("SUITABLE")) {
    return { label: "Start your TESP Skills Scan", url: `${SITE_URL}/skills-scan` }
  }
  return { label: "Book a free consultation call", url: `${SITE_URL}/book-a-call` }
}

// Build the branded HTML email around the AI-generated prose + the code-built
// summary. All styling, the CTA, the summary and the disclaimer are controlled
// here in code — the AI only supplies the framing paragraphs and subject.
function renderHtml(gen: GeneratedEmail, highlights: string[], cta: { label: string; url: string }): string {
  const paragraphs = gen.paragraphs.map((p) => `<p style="margin:0 0 14px;">${esc(p)}</p>`).join("")
  const highlightsHtml = highlights.map((h) => `<li style="margin:0 0 8px;padding-left:4px;">${esc(h)}</li>`).join("")

  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1f2937;line-height:1.6;">
  <span style="display:none;max-height:0;overflow:hidden;opacity:0;">${esc(gen.preheader)}</span>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:24px 0;">
    <tr><td align="center">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:14px;overflow:hidden;border:1px solid #e5e7eb;">
        <tr><td style="background:#1d4ed8;padding:22px 28px;">
          <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;">EWA Tracker Ltd</p>
          <p style="margin:4px 0 0;color:#bfdbfe;font-size:13px;">Level 3 Experienced Worker Assessment &amp; the route to your ECS Gold Card</p>
        </td></tr>
        <tr><td style="padding:28px;">
          <p style="margin:0 0 14px;font-size:16px;">Hi ${esc(gen.greetingName)},</p>
          ${paragraphs}
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:8px 0 20px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;">
            <tr><td style="padding:16px 18px;">
              <p style="margin:0 0 10px;font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#1d4ed8;">Your position at a glance</p>
              <ul style="margin:0;padding:0 0 0 18px;font-size:14px;">${highlightsHtml}</ul>
            </td></tr>
          </table>
          <table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 22px;">
            <tr><td style="border-radius:8px;background:#1d4ed8;">
              <a href="${cta.url}" style="display:inline-block;padding:12px 22px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">${esc(cta.label)} &rarr;</a>
            </td></tr>
          </table>
          <p style="margin:0 0 6px;font-size:13px;color:#6b7280;">Prefer to talk it through? <a href="${SITE_URL}/book-a-call" style="color:#1d4ed8;">Book a free consultation call</a> and we'll confirm your exact starting point.</p>
          <p style="margin:16px 0 0;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;">
            This is an automated guide based on the answers you provided and is indicative only — it is not a guarantee of eligibility, a formal assessment, or a fixed quote. Your qualifications, experience and eligibility are verified during the TESP skills scan and a consultation call. The 18th Edition, Inspection &amp; Testing and AM2E are undertaken with separate providers.
          </p>
        </td></tr>
      </table>
      <p style="margin:16px 0 0;font-size:11px;color:#9ca3af;">EWA Tracker Ltd &middot; EAL Approved Centre</p>
    </td></tr>
  </table>
</body>
</html>`
}

// Generate the framing prose with AI, grounded in the candidate's answers.
async function generateEmailContent(meta: EligibilityLogMetadata): Promise<GeneratedEmail> {
  const firstName = (meta.candidateName || "").trim().split(/\s+/)[0] || "there"

  const cleanCode = cleanPathwayCode(meta.pathway)
  const qualificationRef = cleanCode ? `${QUALIFICATION_NAME} (${cleanCode})` : QUALIFICATION_NAME
  const needsEdition = /no 18th/i.test(meta.bs7671Status || "")
  const needsIT = /no inspection/i.test(meta.itStatus || "")

  // Facts passed to the model for context only. It must communicate, not judge.
  const answerSummary = [
    `First name: ${firstName}`,
    `Experience (self-declared): ${meta.experience || "(not given)"}`,
    `Level 2 qualification (self-declared): ${meta.level2Qualification || "(not given)"}`,
    `Level 3 qualification (self-declared): ${meta.level3Qualification || "(not given)"}`,
    `18th Edition (BS 7671) (self-declared): ${meta.bs7671Status || "(not given)"}`,
    `Inspection & Testing (self-declared): ${meta.itStatus || "(not given)"}`,
    `Main type of work (self-declared): ${meta.workType || "(not given)"}`,
    `Indicative result: ${friendlyResult(meta.eligibilityResult)}`,
    `Qualification to reference: ${qualificationRef}`,
    `18th Edition still to be completed as part of the route: ${needsEdition ? "YES" : "no / already reported"}`,
    `Inspection & Testing still to be completed as part of the route: ${needsIT ? "YES" : "no / already reported"}`,
  ].join("\n")

  const system = `You write warm, concise, personalised follow-up emails on behalf of EWA Tracker Ltd, an EAL
approved centre delivering the ${QUALIFICATION_NAME} (EWA) — the route to the ECS Gold Card for
experienced UK electricians.

The knowledge base below is BACKGROUND to keep your wording accurate. It is NOT a script, and you must
never quote equivalence tables or level mappings from it to the candidate.
<knowledge_base>
${ASSISTANT_KNOWLEDGE}
</knowledge_base>

ABSOLUTE RULES — these protect the centre and must never be broken:
1. You only COMMUNICATE; you never JUDGE. Every answer is SELF-DECLARED by the candidate. NEVER state or
   imply that any qualification "meets", "satisfies", "counts as", "is equivalent to", or "covers" any
   level or entry requirement, and never map a qualification to a level (e.g. do NOT say "236 Part 1 and
   Part 2 meet the Level 2 and Level 3 requirements"). Only say the candidate has REPORTED holding them,
   and that their qualifications and experience will be VERIFIED as part of the formal eligibility and
   skills-scan process. Whether something counts is decided by that process, not by you.
2. GUIDE, DON'T GUARANTEE. The result is indicative only. Never promise eligibility, a place, a pass, or
   a cost. Use soft wording such as "based on what you've told us, you appear potentially suitable".
3. NEVER invent services, offers or actions. Do NOT say the centre recommends providers, sources or
   arranges training, or finds qualifications for people, unless the knowledge base explicitly states it.
4. Frame any missing items (e.g. 18th Edition, Inspection & Testing) correctly: they are NOT reasons for
   rejection and NOT unrelated extras. They are requirements that must ultimately be satisfied as the
   candidate progresses through the route towards the EWA and the ECS Gold Card, and will be identified
   and explained during the full review. The 18th Edition, Inspection & Testing and AM2E are undertaken
   with separate providers.
5. Keep it tight: 2-3 short paragraphs. You may briefly acknowledge, in one sentence, the main things the
   candidate reported as "positive indicators" for the Experienced Worker route — but do NOT itemise
   every answer, because a separate "at a glance" summary (added automatically after your paragraphs)
   already lists them. Avoid repeating that summary.
6. Refer to the qualification by the exact name/number provided ("Qualification to reference"). Never
   append internal suffixes or invent a different code.
7. UK English, professional and friendly. Plain text only — no markdown, no HTML, no emojis. Do NOT
   include a sign-off or signature (the template adds branding).`

  const prompt = `Write the personalised eligibility follow-up email.
Greet the candidate by first name: "${firstName}".

Context (self-declared answers — communicate, do not judge):
${answerSummary}`

  const { object } = await generateObject({
    model: "openai/gpt-4.1-mini",
    schema: emailSchema,
    system,
    prompt,
  })

  return { ...object, greetingName: object.greetingName?.trim() || firstName }
}

// Public entry point. Generates and sends the personalised email. Throws on
// failure so the caller can log it — but the caller must NOT fail the request.
export async function sendEligibilityAutoResponse(meta: EligibilityLogMetadata): Promise<void> {
  const email = (meta.email || "").trim()
  if (!email || !isValidEmail(email)) return // Nothing to send to.

  const gen = await generateEmailContent(meta)
  const highlights = buildHighlights(meta)
  const cta = pickCta(meta.eligibilityResult || "")
  const html = renderHtml(gen, highlights, cta)

  const resend = await getResend()
  const res = await resend.emails.send({
    from: FROM,
    to: [email],
    bcc: [ADMIN_EMAIL], // Keep a copy so the business sees what went out.
    subject: gen.subject,
    html,
  })
  if (res.error) {
    throw new Error(`Resend rejected eligibility auto-response: ${JSON.stringify(res.error)}`)
  }
}
