// Automated, personalised eligibility-response email.
//
// Triggered from /api/eligibility-checker/log whenever a candidate completes an
// eligibility check (AI wizard OR website form) and provided an email address.
// The email content is generated by AI (Vercel AI Gateway, zero-config — same
// setup as the site chatbot) grounded in the knowledge base and the candidate's
// own answers, then delivered via the existing Resend setup.
//
// Tone: GUIDE, DON'T GUARANTEE — personalised and encouraging, but eligibility
// is always framed as indicative and confirmed on a call / skills scan.

import { generateObject } from "ai"
import { z } from "zod"
import { ASSISTANT_KNOWLEDGE } from "@/lib/assistant/knowledge"

// The shape of the metadata the /log route already assembles.
export interface EligibilityLogMetadata {
  candidateName?: string
  email?: string
  phone?: string
  experience?: string
  level2Qualification?: string
  level3Qualification?: string
  bs7671Status?: string
  itStatus?: string
  workType?: string
  pathway?: string
  eligibilityResult?: string
  recommendations?: string
  source?: string
}

const FROM = process.env.RESEND_FROM_EMAIL || "EWA Tracker <bookings@ewatracker.co.uk>"
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "admin@ewatracker.co.uk"
const SITE_URL = (process.env.NEXT_PUBLIC_MARKETING_WEBSITE_URL || "https://www.ewatracker.co.uk").replace(/\/$/, "")

// Basic sanity check so we never try to email an obviously invalid address.
function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

async function getResend() {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) throw new Error("RESEND_API_KEY environment variable is not set")
  const { Resend } = await import("resend")
  return new Resend(apiKey)
}

// Escape user/AI-provided text before putting it into the HTML template.
function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

const emailSchema = z.object({
  subject: z.string().describe("Concise, personalised email subject line. No emojis."),
  preheader: z.string().describe("Short preview text shown in the inbox, under 90 characters."),
  greetingName: z.string().describe("The first name to greet the candidate by, or 'there' if unknown."),
  paragraphs: z
    .array(z.string())
    .min(2)
    .max(4)
    .describe("2-4 short, warm, personalised paragraphs of plain text (no HTML, no markdown)."),
  highlights: z
    .array(z.string())
    .min(2)
    .max(5)
    .describe("2-5 short bullet points summarising their position and what the EWA route involves for them."),
})

type GeneratedEmail = z.infer<typeof emailSchema>

// Decide the primary call-to-action from the eligibility result.
function pickCta(result: string): { label: string; url: string } {
  const r = (result || "").toUpperCase()
  if (r.includes("SUITABLE")) {
    return { label: "Start your TESP Skills Scan", url: `${SITE_URL}/skills-scan` }
  }
  return { label: "Book a free consultation call", url: `${SITE_URL}/book-a-call` }
}

// Build the branded HTML email around the AI-generated content. The template
// (and therefore all styling, the CTA and the disclaimer) is controlled here in
// code — the AI only supplies the prose — so nothing can be spoofed or broken.
function renderHtml(gen: GeneratedEmail, cta: { label: string; url: string }): string {
  const paragraphs = gen.paragraphs.map((p) => `<p style="margin:0 0 14px;">${esc(p)}</p>`).join("")
  const highlights = gen.highlights
    .map(
      (h) =>
        `<li style="margin:0 0 8px;padding-left:4px;">${esc(h)}</li>`,
    )
    .join("")

  return `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;background:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1f2937;line-height:1.6;">
  <span style="display:none;max-height:0;overflow:hidden;opacity:0;">${esc(gen.preheader)}</span>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:24px 0;">
    <tr><td align="center">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#ffffff;border-radius:14px;overflow:hidden;border:1px solid #e5e7eb;">
        <tr><td style="background:#1d4ed8;padding:22px 28px;">
          <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;">EWA Tracker Ltd</p>
          <p style="margin:4px 0 0;color:#bfdbfe;font-size:13px;">Level 3 Experienced Worker Assessment &amp; the route to your ECS Gold Card</p>
        </td></tr>
        <tr><td style="padding:28px;">
          <p style="margin:0 0 14px;font-size:16px;">Hi ${esc(gen.greetingName)},</p>
          ${paragraphs}
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:8px 0 20px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:10px;">
            <tr><td style="padding:16px 18px;">
              <p style="margin:0 0 10px;font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#1d4ed8;">Your position at a glance</p>
              <ul style="margin:0;padding:0 0 0 18px;font-size:14px;">${highlights}</ul>
            </td></tr>
          </table>
          <table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 0 22px;">
            <tr><td style="border-radius:8px;background:#1d4ed8;">
              <a href="${cta.url}" style="display:inline-block;padding:12px 22px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">${esc(cta.label)} &rarr;</a>
            </td></tr>
          </table>
          <p style="margin:0 0 6px;font-size:13px;color:#6b7280;">Prefer to talk it through? <a href="${SITE_URL}/book-a-call" style="color:#1d4ed8;">Book a free consultation call</a> and we'll confirm your exact starting point.</p>
          <p style="margin:16px 0 0;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;">
            This is an automated guide based on the answers you provided and is indicative only — it is not a guarantee of eligibility, a formal assessment, or a fixed quote. Your eligibility is confirmed during the TESP skills scan and a consultation call. The 18th Edition, Inspection &amp; Testing and AM2E are taken with separate providers.
          </p>
        </td></tr>
      </table>
      <p style="margin:16px 0 0;font-size:11px;color:#9ca3af;">EWA Tracker Ltd &middot; EAL Approved Centre</p>
    </td></tr>
  </table>
</body>
</html>`
}

// Generate the email prose with AI, grounded in the knowledge base + answers.
async function generateEmailContent(meta: EligibilityLogMetadata): Promise<GeneratedEmail> {
  const firstName = (meta.candidateName || "").trim().split(/\s+/)[0] || "there"

  // Derive explicit, grounded facts from the human-readable answer labels so the
  // AI states "what's needed" accurately rather than inferring.
  const needsEdition = /no 18th/i.test(meta.bs7671Status || "")
  const needsIT = /no inspection/i.test(meta.itStatus || "")

  const answerSummary = [
    `Name: ${meta.candidateName || "(not given)"}`,
    `Experience: ${meta.experience || "(not given)"}`,
    `Level 2 qualification: ${meta.level2Qualification || "(not given)"}`,
    `Level 3 qualification: ${meta.level3Qualification || "(not given)"}`,
    `18th Edition (BS 7671): ${meta.bs7671Status || "(not given)"}`,
    `Inspection & Testing: ${meta.itStatus || "(not given)"}`,
    `Main type of work: ${meta.workType || "(not given)"}`,
    `Indicative result: ${meta.eligibilityResult || "(not given)"}`,
    `Suggested pathway code: ${meta.pathway || "(not given)"}`,
    `Suggested next step: ${meta.recommendations || "(not given)"}`,
    `Needs to complete 18th Edition: ${needsEdition ? "YES" : "no / already held"}`,
    `Needs to complete Inspection & Testing: ${needsIT ? "YES" : "no / already held"}`,
  ].join("\n")

  const system = `You write warm, concise, personalised follow-up emails on behalf of EWA Tracker Ltd,
an EAL approved centre delivering the Level 3 Electrotechnical Experienced Worker Assessment (EWA)
and the route to the ECS Gold Card for experienced UK electricians.

Ground every fact ONLY in the knowledge base below and the candidate's answers. Never invent prices,
requirements, dates, or qualifications.
<knowledge_base>
${ASSISTANT_KNOWLEDGE}
</knowledge_base>

RULES:
- GUIDE, DON'T GUARANTEE. Their result is indicative only. Never promise eligibility, a guaranteed
  pass, or a fixed total cost. Encourage the next step (skills scan or a free call) to confirm.
- Be specific to THEIR answers: acknowledge the qualifications/experience they hold, and gently note
  any gaps (e.g. 18th Edition or Inspection & Testing) framed as things that can be completed as part
  of the pathway — never as a rejection.
- Remind them, only where relevant, that the 18th Edition, Inspection & Testing and AM2E are taken
  with separate providers.
- UK English. Friendly and professional. Plain text only in paragraphs and bullets — no markdown,
  no HTML, no emojis. Do not include a sign-off or signature (the template adds branding).`

  const prompt = `Write the personalised eligibility follow-up email for this candidate.
Greet them by first name: "${firstName}".

Their eligibility check answers:
${answerSummary}`

  const { object } = await generateObject({
    model: "openai/gpt-4.1-mini",
    schema: emailSchema,
    system,
    prompt,
  })

  // Ensure the greeting name is sensible even if the model deviates.
  return { ...object, greetingName: object.greetingName?.trim() || firstName }
}

// Public entry point. Generates and sends the personalised email. Throws on
// failure so the caller can log it — but the caller must NOT fail the request.
export async function sendEligibilityAutoResponse(meta: EligibilityLogMetadata): Promise<void> {
  const email = (meta.email || "").trim()
  if (!email || !isValidEmail(email)) return // Nothing to send to.

  const gen = await generateEmailContent(meta)
  const cta = pickCta(meta.eligibilityResult || "")
  const html = renderHtml(gen, cta)

  const resend = await getResend()
  const res = await resend.emails.send({
    from: FROM,
    to: [email],
    bcc: [ADMIN_EMAIL], // Keep a copy so the business sees what went out.
    subject: gen.subject,
    html,
  })
  if (res.error) {
    throw new Error(`Resend rejected eligibility auto-response: ${JSON.stringify(res.error)}`)
  }
}
